### ISSUE TITLE
Does the scanning feature work?

### ISSUE THREAD

**Issue by robross0606** [RobLoach/libretro-dolphin-launcher#18] opened 2018-04-28 14:17 UTC
I've compiled your 1.1.1 core and installed it so that it is recognized by RetroArch 1.7.2.  I am able to select the core and have it appear as selected in the overlay.  However, when I attempt to scan my directory of WBFS files, it appears to be slowly scanning through the available files and shows the WBFS names in Yellow on the overlay.  However, once all 47 files are scanned, nothing ever appears in a column on the UI.  Does this core still work with RetroArch 1.7.2?  Does the scanning feature work?

**Comment by RobLoach** [comment] 2018-04-28 14:51
Unsure we have a database of the WBFS files. Where are those from?

There's also the [Dolphin libretro core](https://github.com/libretro/dolphin), which could use an update.

**Comment by robross0606** [comment] 2018-04-28 14:51
https://fileinfo.com/extension/wbfs
Dolphin recognizes these files as well.

**Comment by RobLoach** [comment] 2018-04-28 14:52
Is there a database of WBFS files?

**Comment by robross0606** [comment] 2018-04-28 14:55
There must be since [WiibackupManager](http://www.wiibackupmanager.co.uk/downloads.html) uses it to pull everything, including cases (back and front) and disc images.  I believe it uses [GameTDB](https://www.gametdb.com/Wii/).

**Comment by robross0606** [comment] 2018-04-28 14:56
What file format is your scanner expecting?

**Comment by robross0606** [comment] 2018-04-28 14:59
FYI, the benefit of using WBFS is that it doesn't pad the discs out to 4.7GB like ISO files.  So you save a TON of space since most Wii games don't come close to filling a 4.7GB DVD ISO.

**Comment by RobLoach** [comment] 2018-04-28 15:36
RetroArch supports scanning ISO files, via the serial scanner.  For WBFS games, it likely checks the CRC of the files, which unfortunately won't match.

If you take a look at the playlist files directly, you can see they're pretty easy to make yourself. We could likely improve [RetroArch Playlist Editor](http://www.marcrobledo.com/retroarch-playlist-editor/) to make it easier.

**Comment by robross0606** [comment] 2018-04-28 16:14
Not sure I understand what you mean by the CRC of the files.  I'm aware of what a CRC is, but not why it "won't match".  Wii games typically match a five digit alpha-numeric code that is in the file name and I believe embedded in the wbfs file header. This is how Dolphin and pretty much every actual Wii launcher (USBLoaderGX, WiiFlow, CfgLauncher, etc.) works with WBFS.  Ref:  https://www.gametdb.com/Wii/list

Against what CRC is RetroArch checking?

**Comment by RobLoach** [comment] 2018-04-28 17:25
The CRC32 of the file is not the same as the Serial.

We could accomplish serial scanning of WBFS files with this: https://github.com/libretro/RetroArch/issues/6649

The libretro-database already has those IDs, it just needs to be able to detect what the ID is for a given file.

**Comment by RobLoach** [comment] 2018-04-29 16:50
Mind getting the RetroArch daily and trying this out? Or re-compiling `master` yourself? The change was just merged.

**Comment by robross0606** [comment] 2018-04-29 18:02
Wow, that was fast!  I'll check it out as soon as I can.

**Comment by robross0606** [comment] 2018-04-30 01:55
Do I need to download the whole thing or just one or more core(s)?

**Comment by robross0606** [comment] 2018-04-30 02:17
Looks good so far.  Doesn't appear to have pulled any artwork, but the scanning worked and the names of the games are look correct.  That was incredibly responsive work.  Thanks!

**Comment by robross0606** [comment] 2018-04-30 02:18
That being said, when I actually tried to launch one of them with your dolphin-launcher, I got nothing but a blank screen.  Baby steps I guess. ;)

**Comment by RobLoach** [comment] 2018-04-30 03:37
Check the logs... This core just tries to launch the external program. Blank screen makes sense, since it just tries to launch it, and then shows a blank screen.

**Comment by robross0606** [comment] 2018-04-30 03:38
Not sure I understand why that would show a blank screen.  Shouldn't it actually launch the ROM through Dolphin?

**Comment by i30817** [comment] 2018-05-06 08:55
You should probably remove your installed dolphin core (not the launcher) and remove your playlists and regenerate them. If you try to launch a game with a core once, it 'remembers' that.

I had the same trouble - there is probably a real bug in retroarch of the core wrong core being launched with bogus arguments or if you uninstalled it or something, but once i did the above, it started launching dolphin (not in fullscreen unfortunately).

edit: apparently the dolphin-emu-nogui doesn't actually use the Dolphin.ini from standalone. This is a upstream bug:
https://bugs.dolphin-emu.org/issues/11081

edit2: bug was caused by XDG_CONFIG_HOME override. I overrided it for retroarch and it spread to the dolphin subprocess doh.

**Comment by robross0606** [comment] 2018-05-19 15:53
Soo... what does this mean?  I'm not quite sure *how* to remove a core other than to find the library file and manually delete it.  Is this necessary or has an update been committed to resolve this?

**Comment by i30817** [comment] 2018-05-19 16:46
I mean that when i had the 'dolphin core'  and uninstalled it and installed the 'dolphin launcher' installed games tried to start the 'dolphin core'.

This was actually because i had started them before on that core and playlists store the core that last started the game as a way to let the user force a alternative. So you might be 'failing' to start because it's trying to start a core that you uninstalled. Either deleting the playlist and rescanning it or 'resetting' the affected entries could solve it, and i suggested downloading the databases (from the RA gui) because WBFS files were added recently and the database *doesn't* self-updates (as far as i can tell).

So:
1. update the databases from Online Updater -> Update Databases
2. Either delete the Wii playlist on the retroarch folder/playlists and rescan or reset each entry to remove any stale core association and rescan (to get the WBFS entries if you don't have them yet).

**Comment by robross0606** [comment] 2018-05-19 17:27
How did you "uninstall" a core?  I see no obvious method of doing that other than manually hunting down and removing .info and .so files.

**Comment by RobLoach** [comment] 2018-05-19 18:10
Blank screen, without Dolphin launching, usually means something wrong happened. As I mentioned, post the logs and they may show something relevant.

> How did you "uninstall" a core? I see no obvious method of doing that other than manually hunting down

Correct... It's usually in RetroArch's core directory... ~/.config/retroarch/cores I believe. Alternatively, you can use "Reset Core Association" on the menu entry to let you choose which core to use when launching.

**Comment by robross0606** [comment] 2018-05-20 14:00
I tried all that and it still isn't working.  I simply get a "black" screen.  I put "black" in quotes because it isn't quite black.  It is a very dark grey 4:3 area scaled to the full screen, with vertical letterboxing.  Where can I find the log files for retroarch?  They're not in /var/log or in my user directory.
I ran retroarch from the command line and have attached the output from attempting to launch a game that was successfully scanned:
```
sh: 1: dolphin-emu-nogui: not found
libretro-dolphin-launcher: dolphin-emu-nogui not found. Attempting dolphin-emu...

(dolphin-emu:3018): Gdk-WARNING **: 10:07:01.419: /build/gtk+2.0-AoeliP/gtk+2.0-2.24.32/gdk/x11/gdkdrawable-x11.c:952 drawable is not a pixmap or window
The program 'dolphin-emu' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 29 error_code 3 request_code 3 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
terminate called without an active exception
Aborted (core dumped)
libretro-dolphin-launcher: dolphin-emu not found. Attempting Flatpak...
sh: 1: flatpak: not found
libretro-dolphin-launcher: Failed running Dolphin. Install it and try again.
sh: 1: dolphin-emu-nogui: not found
libretro-dolphin-launcher: dolphin-emu-nogui not found. Attempting dolphin-emu...
```
It would appear that it cannot find `dolphin-emu-nogui`.  Even though I have Dolphin installed, it is true that this executable does not appear to exist.  However, `dolphin-emu` does exist and this claims it cannot find that either.  I can run Dolphin directly and launch games with no issue.

**Comment by robross0606** [comment] 2018-05-20 14:35
Okay!  Figured that out.  Turns out the PPA for Ubuntu didn't install the "nogui" version for some reason.  I removed it and reinstalled with `apt install dolphin-emu-master` again and this time I got the "nogui" executable.  Now retroarch is loading the apps without issue -- and in full screen!
Now if I could just get the Wiimote working in Retroarch... :)

**Comment by i30817** [comment] 2018-05-20 17:02
no-gui is new i think so it's not on stable. I actually opened a issue on dolphin to allow 'no-gui' on KMS environments like most retroarch cores can run (once, because of a bug)..

**Comment by robross0606** [comment] 2018-05-20 17:04
Think I'm pretty good here.  The only last place I'm stuck is trying to get the Wiimote to work in both the Retroarch UI and Dolphin once it starts up.  I have it working in Retroarch now, but seems like the instructions for doing that block it from being detected and used in Dolphin.

**Comment by i30817** [comment] 2018-05-20 17:07
I don't actually have a real wiimote so i can't help you. I simply play games compatible with the classical controller (or the gamecube controllers, which are often the same). The dolphin wiki has a tag listing them all.

**Closed as completed** 2018-05-20 17:07 UTC

**Comment by RobLoach** [comment] 2018-05-20 20:02
There's another issue to discover where Dolphin in https://github.com/RobLoach/libretro-dolphin-launcher/issues/3

Could probably check for nogui or yesgui options.
